ci(track): bump upload-charm action to 2.6.2
canonical/admission-webhook-operator pull request #142
Opened 2024-07-11 08:18 UTC by orfeas-k

Ref canonical/bundle-kubeflow#962

2024-07-12 20:13 UTC, DnPlas submitted a review, later dismissed

2024-07-12 20:14 UTC, DnPlas commented
@orfeas-k after merging this PR, make sure you also merge https://github.com/canonical/admission-webhook-operator/pull/134

2024-07-12 20:15 UTC, DnPlas requested changes

2024-07-12 20:15 UTC, DnPlas commented on .github/workflows/publish.yaml
We need to bump the version in the release job as well.

2024-07-15 08:59 UTC, misohu commented on .github/workflows/publish.yaml
We agreed that the release job did not update so this is not needed. Check jira for more info.

2024-07-15 08:59 UTC, misohu approved these changes
Good job.

2024-07-15 11:39 UTC, merged